### PR TITLE
Adds option property `devToolsOptions` for configuring dev-tools-extension.

### PR DESCRIPTION
**Pull request by lukaswelinder**
## Description
* Extended `interface DevToolsOptions` to support all top level devtools-extension options according to their [docs](http://extension.remotedev.io/docs/API/Arguments.html).
* Added `devToolsOptions` property to bootstrap function's `options` argument to allow customization of dev-tools. This argument defaults to what was already defined.

## Related Issue
Add `devToolsOptions` support to `bootstrap` function. #89 
[blocked by] Tests fail to run. #90

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Please see #90 regarding testing. I'm not too familiar with typescript and could use some help sorting out the issue before moving forward with testing the change I have made.

### CODE REVIEW

**Comment by remojansen** [comment]
@lukaswelinder Thanks for the PR :+1:   and sorry for the build issue. I will be able ti fix it this evening but If you have time please feel free to send more commits to fix the issue.

**Comment by lukaswelinder** [comment]
@remojansen Thanks for the follow up; apologies for the delated response.

I don't have much time to be honest; I've temporarily made an installable git branch for my team until the issue has been resolved. Changes introduced by this PR are working safely in production, but it would be nice to get this resolved and merged.

If I knew what the root problem was (w/ #90), then I would resolve it and make a different PR, but I'm not too familiar with typescript and don't have a whole lot of free time at the moment. 

However, if you can resolve the issues with the errors in the test stubs, or at least point me in the right direction, then I will update this PR with docs and tests covering the changes.

Cheers,
Lukas Welinder

**Comment by lukaswelinder** [comment]
@remojansen Had a few minutes of down-time tonight; I have resolved the issue with the test environment mentioned in #90.

It seems to be an issue with typings around the `connect` method in `react-redux`:

Some info here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9951
Possibly related to: https://stackoverflow.com/questions/42421501/error-ts2345-argument-of-type-t-is-not-assignable-to-parameter-of-type-objec

My solution was to import `connect` within the stubs using `require`, which sets all types to `any`. Not ideal, the tests are now running and passing. 

I would appreciate your input on the issue. I'll move forward with documenting and testing changes in this PR in the meantime.

**Comment by lukaswelinder** [comment]
Oh, I accidentally formatted the stubs file to your lint settings. Strange that it forced a diff on everything though... Let me know if you want me to roll that back.

**Comment by remojansen** [comment]
Thanks a lot for the PR :+1:

**Pull request merged**
